name: "Push to Repository"
description: "Mirrors current repository to another repository."
inputs:
  repository_url:
    description: "URL to destination repository. Based on the following syntax: github.com/BorisStrahilov/myRepositoy"
    required: true
  repository_username:
    description: "Username used for authentication"
    required: true
  repository_password:
    description: "Password used for authentication"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'